### PR TITLE
Seperate signs API from signs definitions

### PR DESCRIPTION
**Pull request by Thomas--S**

### CODE REVIEW

**Comment by pyrollo** [comment]
That's a good idea to separate the sign api from the mod. At first, this mod was just a use case demo for display lib.

I'm thinking about names. It would be better to have homogeneous names for mods, So as we have display_lib and font_lib, signs_api shoud be signs_lib but it would conflict with minetest-mods/signs_lib.

I see tree possibilities : 

- **display_lib** / **font_lib** / **sign_lib** (but sign_lib is very close to signs_lib)

- **display_api**  / **font_api** / **signs_api** (but AFAIK, it's more usual to use _lib ending)

- Merge signs api in **font_lib**

And for the remaining, signs mod, I'll rename it signs_basic or something like that (this implies use of aliases for compatibility reasons).

I'm still thinking about that. What is your opion ?

**Comment by Thomas--S** [comment]
After thinking about this, I actually prefer display_api / font_api / signs_api.

In my opinion, the first option would cause too much confusion with the other signs mod.

The third option would solve the name problem, but I prefer to separate font_lib from signs_api. Both APIs are designed for different usages. font_lib is a more general approach, while signs_api is very specialized.

Please tell me your choice, when you have decided what option you prefer, then I'll update this PR accordingly.

Thanks!

**Comment by pyrollo** [comment]
Let's go for display_api / font_api / signs_api.
I'll change the signs mod name the.next time I'll do significant things on it.
Thank you :)

**Comment by Thomas--S** [comment]
Thanks for your comment!
I'll update the PR accordingly tomorrow.

**Comment by Thomas--S** [comment]
I didn't have enough time to finish this today, maybe I can update this PR tomorrow.

**Comment by Thomas--S** [comment]
The PR is updated now.

Please test this before merging. This is a rather large change, and I cannot guarantee that I didn't overlook a mistake. However, I tested this briefly, and it seems to work.

Thanks!

**Comment by pyrollo** [comment]
PR tested and merged :)
Thanks for that work !

**Comment by Thomas--S** [comment]
Thanks for merging!

**Pull request merged**
