### PR TITLE
Allow a greater object offset

### PR DESCRIPTION
**Pull request by Thomas--S**
This allows e.g. polemounted signs.
Required for display_modpack to be usable in the streets mod.
Backwards compatible.

### CODE REVIEW

**Comment by Thomas--S** [comment]
For a possible use case please see minetest-streets/streets#98.

**Comment by Thomas--S** [comment]
PR updated to fix problems at mapblock borders. Should be ready for merge now.

**Comment by pyrollo** [comment]
Nice PR ! I'll test it this week end

**Comment by pyrollo** [comment]
Hi Thomas, 

I did a simple test with your version and I had some troubles. It seems to work on a new world but on an already exiting world with signs there's a problem.

Here is how to easily get that problem:
- Create a new world with my version of display_modpack (current version);
- Place a single sign with text (any signs or signs_road sign);
- Shut down minetest and upgrade to the PR version;
- Restart minetest

Sign does not display text anymore and, when exiting minetest, there are lots of "Trying to store id = XXXX statically but block (X,Y,Z) already contains 64 objects. Forcing delete." messages.

I added a print just before add_entity at line 134 of display_api/init.lua and saw that hundred of entities are being added for a single sing.

I have to get more into your code to understand what happens.

**Comment by Thomas--S** [comment]
Thanks for finding this problem!

It seems like I introduced this bug after testing backwards compatibility while doing little improvements.
The problem is fixed now.

.


`display_api/init.lua` Line 87:
```lua
return vector.equals(real_pos, vector.round(pos))
```

The `vector.round` in this line was missing.

**Comment by Thomas--S** [comment]
Thank you very much for merging this!

**Pull request merged**
