### PR TITLE
Update the entities as soon as mapblock is loaded

### PR DESCRIPTION
**Pull request by Thomas--S**
Useful e.g. after /clearobjects
Introduces the group `display_lib_sign`

### CODE REVIEW

**Comment by pyrollo** [comment]
Very good idea and a last, it solves the /clearobjects issue :+1: 

I have a remark, this is not only a signs stuff, this should apply also to clocks and steles.

So the group should be named something like "display_lib_entity" instead of "display_lib_sign" and added to clock and steles nodes.

**Comment by Thomas--S** [comment]
Thanks for your answer!

I added the group to clocks and steles now, too. I decided to use the group name `display_lib_node`. I hope this is ok for you.

**Comment by Thomas--S** [comment]
Updated once again because there was still one little mistake left. (Steles were not updated correctly.)

Now it should work fine.

**Comment by pyrollo** [comment]
Yes, that's fine, I was hesitating with this name also :)

**Comment by Thomas--S** [comment]
Thanks for merging!

**Comment by pyrollo** [comment]
Your welcome ! Thanks for the improvement :)

**Pull request merged**
