### PR TITLE
Lossless compression

### PR DESCRIPTION
**Pull request by MoNTE48**

### CODE REVIEW

**Comment by MoNTE48** [comment]
Maybe worth revert svg compression.

**Comment by pyrollo** [comment]
Good improvement in terms of space saving.

Yes, I guess svg should be kept uncompressed, as they are not downloaded in media.

Can you give details about how did you proceeded to improve PNG compression ?

It could be very good to include that process in `make_font_textures.sh` script.

**Comment by MoNTE48** [comment]
@pyrollo svg compression reverted
I use https://github.com/JayXon/Leanify this tool.
I have other utilities for even more texture compression, but they are unlikely to give even more compression.

**Comment by pyrollo** [comment]
Thanks ! Merged :)

**Comment by MoNTE48** [comment]
It turned out 3 commits. I can tell how to squash them in 1

**Pull request merged**
